FROM rust:1.94.1 AS builder
WORKDIR /app

COPY Cargo.toml Cargo.toml
COPY src src

RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /app/target/release/{{repository.name}} /usr/local/bin/{{repository.name}}

ENTRYPOINT ["/usr/local/bin/{{repository.name}}"]
