FROM rust:1.95.0@sha256:4a7e3a0c309c9bab658e469f842711bd595fae484936bc5d605e08ca0c631bf4 AS builder
WORKDIR /app

COPY Cargo.toml Cargo.toml
COPY src src

RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /app/target/release/{{repository.name}} /usr/local/bin/{{repository.name}}
COPY config config
COPY requirements requirements

ENTRYPOINT ["/usr/local/bin/{{repository.name}}"]
