FROM rust:1.94.1@sha256:652612f07bfbbdfa3af34761c1e435094c00dde4a98036132fca28c7bb2b165c AS builder
WORKDIR /app

COPY Cargo.toml Cargo.toml
COPY src src

RUN cargo build --release

FROM debian:bookworm-slim
WORKDIR /app

COPY --from=builder /app/target/release/{{repository.name}} /usr/local/bin/{{repository.name}}
COPY config config
COPY requirements requirements

ENTRYPOINT ["/usr/local/bin/{{repository.name}}"]
